"""Package the final source code zip for Blackboard submission.

Produces ``Group43_source.zip`` at the project root with this layout:

    Group43_source.zip
    ├── source_code/    # pipeline + notebooks + requirements (NO data, NO models)
    └── application/    # Streamlit app + Dockerfile + samples (NO venv, NO cache)

Excluded by design:
    - source_code/data/raw/*       (Kaggle dataset, fetched by Dockerfile)
    - source_code/data/processed/* (regenerated by `python -m pipeline.preprocess`)
    - source_code/models/*.pkl     (linked from report; available on Google Drive)
    - source_code/models/figures/* (regenerated by EDA notebook)
    - any __pycache__, .ipynb_checkpoints, .venv, .git

Run:
    python build_submission.py
"""
from __future__ import annotations

import shutil
import sys
import tempfile
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
GROUP_NUMBER = "43"
OUT = ROOT / f"Group{GROUP_NUMBER}_source.zip"

EXCLUDE_DIRS = {"__pycache__", ".ipynb_checkpoints", ".venv", "venv",
                "env", ".git", ".pytest_cache", ".mypy_cache",
                "node_modules", ".DS_Store"}
EXCLUDE_PATH_FRAGMENTS = (
    "source_code/data/raw/",
    "source_code/data/processed/",
    "source_code/models/",  # excludes .pkl + figures
    ".venv/",
    ".git/",
)
EXCLUDE_EXTS = {".pkl", ".joblib", ".parquet"}


def _should_skip(rel: str) -> bool:
    rel = rel.replace("\\", "/")
    if any(d in rel.split("/") for d in EXCLUDE_DIRS):
        return True
    for frag in EXCLUDE_PATH_FRAGMENTS:
        if rel.startswith(frag):
            return True
    if Path(rel).suffix.lower() in EXCLUDE_EXTS:
        return True
    return False


def _walk(root: Path):
    for p in sorted(root.rglob("*")):
        if p.is_dir():
            continue
        rel = p.relative_to(ROOT).as_posix()
        if _should_skip(rel):
            continue
        yield p, rel


def main() -> None:
    if OUT.exists():
        OUT.unlink()
    written = 0
    with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as zf:
        for folder in ["source_code", "application"]:
            base = ROOT / folder
            if not base.exists():
                print(f"[warn] missing {folder}/")
                continue
            for path, rel in _walk(base):
                zf.write(path, arcname=rel)
                written += 1
        # README at the root for graders.
        readme = ROOT / "README.md"
        if readme.exists():
            zf.write(readme, arcname="README.md")
            written += 1

    size_mb = OUT.stat().st_size / 1024 / 1024
    print(f"[done] {OUT.name}  ({written} files, {size_mb:.2f} MB)")
    print()
    print("Next manual steps:")
    print(f"  1. Open Group{GROUP_NUMBER}_report.docx in Pages/Word, insert 4 Streamlit")
    print("     screenshots + paste the signed VeriGuide receipt, then 'Export as PDF'")
    print(f"     -> Group{GROUP_NUMBER}_report.pdf")
    print(f"  2. Record Group{GROUP_NUMBER}.mp4 demo video (<= 10 min)")
    print("  3. Upload models (.pkl) to a public Google Drive folder; paste")
    print("     the URL into the report's Data Modeling chapter")
    print("  4. Submit to Blackboard > Content > Course Project:")
    print(f"       - Group{GROUP_NUMBER}_source.zip  (this file)")
    print(f"       - Group{GROUP_NUMBER}_report.pdf")
    print(f"       - Group{GROUP_NUMBER}.mp4         (uploaded separately, no group share)")


if __name__ == "__main__":
    main()
